[project]
name = "ai-toolbox"
version = "0.1.0"
requires-python = "==3.12.13"
dependencies = [
    "requests",
    "jupyterlab",
    "python-dotenv",
    "streamlit",
    "openai>=2.31.0",
    "gradio>=6.11.0",
    "ipywidgets>=8.1.8",
    "mlx-whisper>=0.4.3",
    "openai-agents>=0.14.4",
    "sendgrid>=6.12.5",
    "anthropic>=0.49.0",
    "langgraph>=1.2.4",
    "langchain-openai>=1.2.2",
    "langchain-community>=0.4.2",
    "langsmith>=0.8.8",
    "langchain>=1.3.4",
    "langgraph-checkpoint-sqlite>=3.1.0",
    "playwright>=1.60.0",
    "lxml>=6.1.1",
    "langchain-experimental>=0.4.2",
]

